Christin-paige/BuiltInPublic

README.md
I've formatted the tech-stack as a table as I thought it may help make it easier to read
=> Show tech-stack as table for improved clarity

LICENSE, bun.lock
1. First Change - As this repository opensource I am including  APACHE 2.0 LICENSE opensource compatible LICENSE under the name of Christin Paige Martin. 
This LICENSE will enable software distribution and sub-licensing also comply with opensource system.
Maintainer and developers can add or modify this LICENSE according to their needs.
2. Second change - Bun runtime integration , If any developer or contributor using bun as their run time I am adding   dependencies using Bun and further testing so if the app deployed to an edge environment later and using Bun things could go smoothly.
Thank you
=> Added LICENSE

package-lock.json, package.json, tsconfig.json
This is a barebones TypeScript conversion that allows JS and will enable us to incrementally update existing code as we go
Adds:
- typescript
- types/react
- types/node
- autogenerated tsconfig.json with strict enabled
=> adds TS, react and node types, and tsconfig

README.md
Reformats image links in README with alt text, and proper routing to `/docs` folder
=> updates image links in README

database.types.ts, next.config.mjs, package-lock.json, package.json, src/app/dashboard/profile/Profile.js, src/app/hook/useUser.tsx, src/app/layout.tsx, src/components/navbar.js, src/components/profileIcon.tsx, src/components/query-provider.tsx, utils/supabase/client.ts, utils/supabase/server.ts
Installed react query
Installed react query dev tools
Created a query provider
Installed generated typescript types for API and Supabase libraries 
Fetched data into profileIcon component, had to add images:remote patterns to next.config file for avatar_url to show in navbar
Added avatar to dashboard in the profile component
=> React query

CONTRIBUTORS.md, SECURITY.md
Created SECURITY.md file, describes our responsible disclosure policy and how to disclose, what details, etc.
Created CONTRIBUTORS.md file, describes how to become a contributor, our secure coding standards, provides examples, lists common vulnerabilities and related mitigations, etc.
=> Security documentation

package-lock.json, package.json, src/setupTests.ts, vitest.config.mts
Adds:
- vitest
- react testing library
- jest-dom testing library
config, setupTests, and npm scripts to launch test runner
=> Setup vitest

src/components/themes-provider.tsx
Included useEffect hook within the theme provider to render the theme on the client side.
You should just not get the nextjs error about the hydration at the bottom of the screen now.
No screenshot necessary.
N/A
=> Fix hydration error with useEffect

src/components/query-provider.tsx
=> changed getSession to getUser

next.config.mjs, src/components/Navbar/Navbar.tsx, src/components/Navbar/actions.ts, src/components/ProfileIcon.tsx, supabase/supabase.types.ts
Made the profile icon/avatar a link within the navbar, and edited the navbar and actions.ts to properly refresh when the user clicks logout.
This is a pretty small change
=> Profile Icon link and logout button fix

package-lock.json, src/app/page.js
Changed 3 properties from class to className to resolve the error
=> Changed dom property names in page.js

package-lock.json, package.json, src/services/Error.service.ts, src/services/UINotification.service.ts
Created a class with methods: success, error, and info to handle toasts notifications in the future and removed Error Service
=> Create Notification service class

scripts/seeds/auth-users.ts
Changed emails to builtinpublic1+testuser1@gmail.com & passwords to: builtinpublic123
n/a
n/a
I will update the wiki with this PR is merged. Also, everyone will have to update their local db instance so it will re-seed with this newly updated data.
=> Change emails & passwords for test users

src/app/(main)/[username]/projects/[id]/page.tsx, src/app/(main)/[username]/projects/page.tsx
Add pages for all projects and single project
=> Add routes for projects

README.md
I have formatted the tech stack as a table for improved readability
- NA
=> reformatted tech stack as a table for easier readability

.github/workflows/syft.yml
**Ticket:** [86aa679b9](https://app.clickup.com/t/86aa679b9)
Create a PR off a branch after this is merged
=> Adding in GitHub action for Syft

.gitguardian.toml, .github/workflows/gitleaks.yml, README.md
**Ticket Number:** [86aa8wmq2](https://app.clickup.com/t/86aa8wmq2)
Can review the output of it running on the PR
=> Adding in updates to gitleaks config and updated README.md

src/app/(main)/dashboard/page.tsx, src/app/(main)/dashboard/profile/Profile.tsx
Replaces dashboard that went missing
=> Fix dashboard

.github/dependabot.yml, .github/workflows/dependabot-security-auto-merge.yml
**Ticket Number:** [86aa679ay](https://app.clickup.com/t/86aa679ay)
Look at this PR see if dependabot is now dependable
=> Fixing up dependabot so it is more dependable

scripts/precheck.sh
Added ESLint and installation checks to precheck.sh to check installation of tools prior to running remainder of script, includes short installation instructions if x tool is missing.
`npm i`
then commit and push changes
=> Add ESLint & installation checks into precheck.sh, prompt to install if x isn't found

src/app/auth/actions.ts
sets login action to use server, uses server side supabase client
=> Server side login

SECURITY.md
Changed the link in the security.md documentation to lead users to the contributors page in the wiki.
=> Change link in security.md for contributors to the wiki page

supabase/migrations/20250517104606_base_tables_rls.sql
**Ticket Number:** [86aafjgr5](https://app.clickup.com/t/86aafjgr5)
Check out branch try to access /dashboard not logged in
- [c] I have conducted a self-review of my code.
=> Updating RLS policy to only show profiles when you login

src/app/(main)/[username]/components/UserInfo.tsx, src/app/(main)/[username]/page.tsx, src/app/layout.tsx, src/contexts/ProfileEditContext.tsx, src/hooks/useProfile/actions.ts, src/repositories/profileRepository/profile.repository.ts, src/repositories/profileRepository/profile.types.ts
Ticket Number: https://app.clickup.com/t/86a9whgjk
- **src/app/(main)/[username]/components/UserInfo.tsx**
- **src/app/(main)/[username]/page.tsx**
- **src/app/layout.tsx**
- **src/contexts/ProfileEditContext.tsx** (new)
- **src/hooks/useProfile/actions.ts**
- **src/repositories/profileRepository/profile.repository.ts**
- **src/repositories/profileRepository/profile.types.ts**
- **UserInfo**: The user profile component now supports inline editing for 'username' and 'bio' fields, and integrates success/error notifications.
- **ProfileEditContext**: A new React context to determine if the current user can edit a profile, enabling or disabling edit controls accordingly.
- **ProfileRepository**: Data layer updated with methods to check username uniqueness and update one or more profile fields …
=> Implement profile editing functionality with username and bio updates

src/app/(main)/[username]/components/UserInfo.tsx
Remove Followers, Following, Posts and counts from left sidebar on Profile.
**Ticket Number:** [86aah9vqf](https://app.clickup.com/t/86aah9vqf)
=> Remove Followers, Following, Posts and counts from left sidebar

utils/supabase/middleware.ts
Addendum to: CU-86aa67brp
Uses `createAnonClient` (http-only cookie version) to create supabase client in middleware
=> uses supabaseAnonClient for middleware

src/app/staging-auth/actions.ts
=> removes console log

.github/workflows/semgrep.yml
Semgrep was silently failing due to config files being in the ci command while logged into Semgrep. Removed config files from workflow, set policies on Semgrep.dev. 
**Ticket Number:** [86aapgnpd](https://app.clickup.com/t/86aapgnpd)
=> Semgrep Fix

.github/workflows/push-migrations.yml
Created workflow to connect to and push merged branches to staging Supabase instance.
**Ticket Number:** [86aa9840g](https://app.clickup.com/t/86aa9840g)
Can't really be tested until it's merged and another branch gets merged after.
=> Create Supabase-Staging Migrations Workflow

.github/workflows/push-migrations-staging.yml
=> updates gh action to deploy changes to sb

.github/workflows/push-migrations-staging.yml
=> Trial SB Staging

.github/workflows/push-migrations-staging.yml
=> Breaking up link & push commands

src/app/(main)/[username]/components/StreakSection.tsx, src/app/(main)/dashboard/feed/Feed.tsx
Unticketed fix to get staging over the line
fixes type errors in unused streak and feed
=> Calendar type fix

src/app/staging-auth/actions.ts
Updates staging-auth cookie to use samesite lax, strict was preventing cookies from being sent after redirecting from auth providers
CU-86aa983qu
=> changes staging cookie samesite to lax

config/private/profanity-list.ts, package-lock.json, package.json, src/use-cases/BaseUseCase.ts, src/use-cases/updateUserProfile/UpdateUserProfile.ts, src/use-cases/updateUserProfile/__tests__/UpdateUserProfile.test.ts, utils/usernameValidator.ts
Closes: CU-86aa95n27
Adds `UserProfileUpdate` use case to handle updating user profile fields.
Adds unit tests
This code has not been integrated yet, just run the tests with `npm run test`
=> Profile update usecase

src/app/(main)/[username]/components/UserInfo.tsx
Updates: CU-86aa9aw0k
Fixes build error regarding nullable usernames
=> fixes build error regarding null user names

.husky/pre-commit, scripts/precheck.sh, src/repositories/projectRepository/project.repository.ts, src/repositories/projectRepository/project.types.ts, supabase/migrations/20250803000000_add_project_updates_table.sql
An empty file was merged to the repo, checks should now be in place to make sure it doesn't happen again.
**Ticket Number:** [86aaum5df](https://app.clickup.com/t/86aaum5df)
=> Check for Empty Files in Pre-Commit and Pre-Push

src/repositories/projectRepository/project.types.ts, supabase/supabase.types.ts
Adjusted the project supabase type and created the project updates type, as well as making the types for projects pascal case.
I don't think there is a way to test it at the moment, just read the code line by line to verify it's correct.
=> Supabase types fix

.prettierrc.yml, src/use-cases/BaseUseCase.ts, src/use-cases/projects/CreateNewProject.ts, src/use-cases/projects/__tests__/CreateNewProject.test.ts, src/use-cases/updateUserProfile/UpdateUserProfile.ts
Closes: CU-86aax9c3n
Adds CreateNewProject use case and tests
Refactors BaseUseCase and UpdateUserProfile use cases (repository is only required in UpdateUserProfile)
reverts prettierrc unknown option
=> Create new project

package-lock.json, package.json, src/app/(main)/[username]/components/FeedSection.tsx, src/app/(main)/onboarding/onboarding-form/OnboardingForm.tsx, src/components/Projects/CreateProject/CreateProjectButton.tsx, src/components/Projects/CreateProject/actions.ts, src/components/Projects/CreateProject/createProject.schema.ts, src/components/ui/dialog.tsx, src/use-cases/projects/CreateNewProject.ts
=> Create new project UI

package.json
Update package.json to install husky not using the deprecated way
**Ticket Number:** [86ab4hf87](https://app.clickup.com/t/86ab4hf87)
1. Checkout branch
2. run `npm i`
3. Ensure it no longer warns of deprecation for husky
=> Updating package.json to setup husky correctly

src/components/Profile/Bio.tsx, src/components/Profile/DisplayName.tsx, src/hooks/useProfile/actions.ts, src/hooks/useProfile/profile.schema.ts
Had to add this fix so the bio would properly update. It was failing before, and I didn't catch it somehow.
Pull changes, run the app, login to test user, and attempt to update the bio.
=> Add display name to the profile mutation data

src/app/(main)/[username]/components/UserInfo.tsx, src/components/Buttons/SignOutBtn.tsx, src/components/Profile/Bio.tsx, src/components/Profile/DisplayName.tsx, src/hooks/useProfile/actions.ts, src/hooks/useProfile/profile.schema.ts, src/hooks/useProfile/useProfile.tsx, src/use-cases/updateUserProfile/UpdateUserProfile.ts
Closes: CU-86ab4xdv0
Relaxes schema validation on bio and display name
refactors bio and display name components to remove profanity checks, and smooth error handling and form reseting
you should be able to add emojis, special characters, and curse words in display name and bios
=> Relax profile schemas

instrumentation-client.ts, next.config.mjs, package-lock.json, package.json
Add Posthog analytics to app (staging and prod only).
**Ticket Number:** [86aah9pth](https://app.clickup.com/t/86aah9pth)
Nothing to really test on dev except to make sure that any Posthog init code doesn't run. It's okay for the Posthog package to show up because that's in `package.json`.
On prod (after the env vars are added), then Posthog should init. I tested this locally and did see it was firing in the Posthog dashboard so I'm pretty sure it should work on prod.
I followed the instructions for [adding Posthog](https://posthog.com/docs/libraries/next-js) to a Next.js 15.3+ app. I wrapped the installation code in an environment check so we don't load it on dev.
**NOTE:** There are 2 environment variables we'll need to add to our production server for this to work. I can send them over …
=> Add posthog-js package and init code

utils/supabase/NextJSCookieStorage.ts
Changed cookieOptions to always be secure to fix the login issue in the dev enviornment.
Try to login with test user or github account
=> Change cookieOptions to always be secure to fix login issue on dev env

src/app/(main)/[username]/components/FeedSection.tsx, src/app/(main)/[username]/page.tsx, src/app/project/[id]/page.tsx, src/components/Projects/ProjectsList.tsx, src/hooks/useProject/useProject.tsx
Corrected the prop drilling, links, and styles for the projects list and page.
Pull the changes, check out a project of testuser3 while logged into test user 1 or another user.
Ensure the url doesn't show the username of that user when you're looking at the project.
Ensure the styles of that persons project page is the same as the test users project that you're logged into.
=> Project list fix

supabase/functions/email-signup-link/index.ts
=> adds exponential back off to email signup function for 429s

src/repositories/base.repository.ts, src/repositories/policyRepository/policy.repository.ts, src/repositories/policyRepository/policy.types.ts
Closes: CU-86ab7zu39
Adds PolicyRepository, updates BaseRepository to allow null value comparison in filters
Nothing to test at this point, if it builds it's good
=> Policy repository

.env.example
=> bump to trigger deployment
